version: '3.8'

services:
  app:
    build: .
    container_name: temp-mail-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SMTP_PORT=2525
    ports:
      - "5000:5000"
      - "2525:2525"
    volumes:
      - ./data:/app/data
    networks:
      - temp-mail-network

  nginx:
    image: nginx:alpine
    container_name: temp-mail-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - temp-mail-network

  certbot:
    image: certbot/certbot
    container_name: temp-mail-certbot
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./webroot:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email your-email@example.com --agree-tos --no-eff-email -d yourdomain.com -d www.yourdomain.com

networks:
  temp-mail-network:
    driver: bridge

volumes:
  data: 